#Server System
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8000
  servlet:
    context-path: /ddbus/


#Mongo
spring:
  application:
    name: tcp_ddbus_wx
  thymeleaf:
    suffix: .ftl
  profiles:
    active: dev


# MyBatis
mybatis:
  mapper-locations: classpath:mapperXml/*.xml

#日志
logging:
  level:
    org:
      springframework: info
      spring:
        springboot:
          dao: info