#Mongo
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: ddbus
    url: jdbc:mysql://120.55.62.88:3306/ddbus?useSSL=FALSE&serverTimezone=GMT%2B8
    username: root
    password: 123456
  data:
    mongodb:
      port: 6001
      database: ddbus
      host: 103.14.132.12
      username: ddbus
      password: evcas2017

